export const FETCH_FILTER_FIELDS_REQUEST = 'FETCH_FILTER_FIELDS_REQUEST';
export const FETCH_FILTER_FIELDS_SUCCESS = 'FETCH_FILTER_FIELDS_SUCCESS';
export const FETCH_FILTER_FIELDS_FAILURE = 'FETCH_FILTER_FIELDS_FAILURE';
