export const FETCH_CART_LIST_REQUEST = 'FETCH_CART_LIST_REQUEST';
export const FETCH_CART_LIST_SUCCESS = 'FETCH_CART_LIST_SUCCESS';
export const FETCH_CART_LIST_FAILURE = 'FETCH_CART_LIST_FAILURE';

export const ADD_CART_ITEM_REQUEST = 'ADD_CART_ITEM_REQUEST';
export const ADD_CART_ITEM_SUCCESS = 'ADD_CART_ITEM_SUCCESS';
export const ADD_CART_ITEM_FAILURE = 'ADD_CART_ITEM_FAILURE';

export const REMOVE_CART_ITEM_REQUEST = 'UPDATE_CART_LIST_REQUEST';
export const REMOVE_CART_ITEM_SUCCESS = 'UPDATE_CART_LIST_SUCCESS';
export const REMOVE_CART_ITEM_FAILURE = 'UPDATE_CART_LIST_FAILURE';

export const FETCH_CART_ITEMS_COUNT_REQUEST = 'FETCH_CART_ITEMS_COUNT_REQUEST';
export const FETCH_CART_ITEMS_COUNT_SUCCESS = 'FETCH_CART_ITEMS_COUNT_SUCCESS';
export const FETCH_CART_ITEMS_COUNT_FAILURE = 'FETCH_CART_ITEMS_COUNT_FAILURE';

export const CHANGE_CART_ITEM_COUNT_REQUEST = 'CHANGE_CART_ITEM_COUNT_REQUEST';
export const CHANGE_CART_ITEM_COUNT_SUCCESS = 'CHANGE_CART_ITEM_COUNT_SUCCESS';
export const CHANGE_CART_ITEM_COUNT_FAILURE = 'CHANGE_CART_ITEM_COUNT_FAILURE';

export const SHOW_ADDED_ITEM_MODAL = 'SHOW_ADDED_ITEM_MODAL';
export const HIDE_ADDED_ITEM_MODAL = 'HIDE_ADDED_ITEM_MODAL';


