export const FETCH_DISCOUNTS_REQUEST = 'FETCH_DISCOUNTS_REQUEST';
export const FETCH_DISCOUNTS_SUCCESS = 'FETCH_DISCOUNTS_SUCCESS';
export const FETCH_DISCOUNTS_FAILURE = 'FETCH_DISCOUNTS_FAILURE';

export const GET_DISCOUNT_CODES_REQUEST = 'GET_DISCOUNT_CODES_REQUEST';
export const GET_DISCOUNT_CODES_SUCCESS = 'GET_DISCOUNT_CODES_SUCCESS';
export const GET_DISCOUNT_CODES_FAILURE = 'GET_DISCOUNT_CODES_FAILURE';

export const ADD_DISCOUNT_CODE_REQUEST = 'ADD_DISCOUNT_CODE_REQUEST';
export const ADD_DISCOUNT_CODE_SUCCESS = 'ADD_DISCOUNT_CODE_SUCCESS';
export const ADD_DISCOUNT_CODE_FAILURE = 'ADD_DISCOUNT_CODE_FAILURE';
